USE [FACEBOOKDB]
GO

ALTER TABLE [dbo].[ADDFRIEND]  WITH CHECK ADD  CONSTRAINT [SAMEUSERCANNOTADD] CHECK  (([AddUserID]<>[ReceiverUserId]))
GO

ALTER TABLE [dbo].[ADDFRIEND] CHECK CONSTRAINT [SAMEUSERCANNOTADD]
GO


